services:
  postgresql:
    image: postgres
    container_name: bootcampPostgres
    environment:
      POSTGRES_USER: desafio
      POSTGRES_PASSWORD: desafio
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U desafio -d desafio"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    container_name: localstack_desafio_sysmap
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=desafio
      - AWS_SECRET_ACCESS_KEY=desafio

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgresql:
        condition: service_healthy
      localstack:
        condition: service_started
